<?php
	class ajaxtable{
		var $DB_table = 'ajaxLab';
		var $dataMount = 26;
		var $dataInsert = 'INSERT INTO ajaxLab (courseKey, program, courseNum, courseName, courseDescription)';
		
		function dataOut(){
			$sqlOut = $this->dataInsert . " VALUES";
			foreach($this->dataString as $row){
				$sqlOut .= $row . ", ";
			}
			$sqlOut = rtrim($sqlOut,', ');
			return $sqlOut . ";";
		}
		
		
		//Kill Table:
		var $killTable = "DROP TABLE IF EXISTS ajaxLab";
		//create table:
		var $createTable = "CREATE TABLE IF NOT EXISTS ajaxLab (courseKey smallint(6) NOT NULL AUTO_INCREMENT, program char(4) NOT NULL, courseNum smallint(6) NOT NULL, courseName varchar(32) NOT NULL, courseDescription text NOT NULL, PRIMARY KEY (courseKey)) ENGINE=MyISAM  DEFAULT CHARSET=latin1 COMMENT='SDEV 250 AJAX lab' AUTO_INCREMENT=27;";
		
		//Data
		var $dataString = array(
"(1, 'CPIN', 239, 'Systems Analysis and Design', 'Students will learn methodologies pertinent to the assessment, design, and implementation of information systems. Students will develop the skills necessary to analyze, design and manage the development of enterprise-scale information systems solutions incorporating contemporary methods and effective organizational and global project management practices. Students will actively participate in discussions, review selected articles, participate in team exercises and collaborate on projects involving analysis and prototyping of\nsystems addressing real-world problems and integrating current and emerging technologies.')",
"(2, 'CPIN', 269, 'Computing and Informatics Projec', 'Students will work within a team to identify and employ methodologies pertinent to the assessment, design and operation of business computer information systems. Teams will analyze and implement established and evolving methodologies for the development of a business-oriented computer environment. Students will develop individual and team competencies working to employ current software tools to generate and illustrate the flow of the actual development of a project. Students are required to demonstrate course objectives through the appropriate certification exam preparation materials and the fee for the exam is assessed upon enrollment in the course.')",
"(3, 'CPIN', 279, 'Computing and Informatics Explor', 'Prepares students for entry into the information world. Reviews procedures for researching a career; preparing a resume and a portfolio; interviewing; team participation; and ethical/productive job performance. Additionally, all associate degree graduates are required to complete a Technical Outcomes Assessment specific to their program. This could be in the form of an assessment exam, a national certification exam, or a portfolio.')",
"(4, 'CSCI', 101, 'Computer Science I', 'Introduces the fundamental concepts of procedural programming. Topics include data types, control structures, functions, arrays, files, and the mechanics of running, testing, and debugging. The course also offers an introduction to the historical and social context of computing and an overview of computer science as a discipline.')",
"(5, 'CSCI', 102, 'Computer Science II', 'Provides a working understanding of the fundamentals of procedural and object-oriented program development using structured, modular concepts and modern object-oriented programming languages. Reviews control structures, functions, data types, variables, arrays, and data file access methods. This is a first-level course in object-oriented computer programming, using a language such as Java or C++. Object-oriented concepts studied include classes, objects, inheritance, exception handling, recursion, abstract data types, streams and file I/O, reusable software, and event-driven programming.')",
"(6, 'CSCI', 105, 'Discrete Logic for Computers', 'This course introduces students to discrete mathematical concepts including reasoning and proof, especially with the discrete phenomenon often used in the field of Computer Science. Students will learn the applicable mathematical vocabulary and its correct usage. Other topics include sets, functions, notation, proofs, proof techniques, relations, induction, counting and countability, probability, and partitions.')",
"(7, 'CSCI', 202, 'Computer Science III', 'Builds on the foundation of CSCI II to provide a working understanding of the fundamentals of data structures and algorithms used in modern computer programming. Introduces a variety of data storage alternatives, including stacks, queues, linked lists, hash tables, trees and graphs. Employs the basics of algorithmic analysis, recursion, language translation and software engineering. Discusses the overview, history and comparison of programming languages, as well as virtual machines and language translation.')",
"(8, 'CSCI', 210, 'Database Systems', 'This course presents the theory and practice of database systems and gives an advanced introduction into the concepts for modeling, designing, querying, and managing large and distributed databases. The emphasis will be on theoretical considerations involved in modeling data and the principles of database systems in a multi-user environment. Students will address issues associated with enterprise database processing with respect to user authentication and development in an application/internet environment.')",
"(9, 'DBMS', 110, 'Database Design and Management', 'Introduces students to the basic concepts of databases including the types of databases, the general database environment, and the importance of data to the business world. Discussion with hands-on activities will include database design, normalization of tables, and development of tables, queries, reports, and applications. Discussions will include database administration and data maintenance. Students will be introduced to data concepts such as data warehousing, data mining and BIG Data. Students will develop a business application using database software such as Microsoft Access. Students will be required to demonstrate skills such as team building, work ethic, communications, documentation, and adaptability. Students are required to demonstrate course objectives through the appropriate Microsoft certification exam and the fee for the exam is assessed upon enrollment in the program. ')",
"(10, 'DBMS', 120, 'Database Server Installation', 'Introduces students to terminology, concepts, theory, and practice of installing, implementing, and maintaining a database server. Discussion will include the relationships between network servers and database servers. Students will explore server virtualization and using data servers in virtual environments. Students will be introduced to database and database server security concepts.')",
"(11, 'DBMS', 130, 'Database Management Using SQL', 'Students are introduced to Structured Query Language (SQL) which is a database computer language used to manage, query, retrieve and manipulate data. Students are introduced to SQL as a high level tool in the management of data in client and server database environments. Students will use relational database management systems such as MySQL, Oracle, and/or SQL Server to develop SQL skills in a lab environment. Students are required to demonstrate course objectives through the appropriate Oracle certification exam and the fee for the exam is assessed upon enrollment in the course.')",
"(12, 'DBMS', 150, 'Oracle Database Administration I', 'Introduces program applications in an Oracle database environment with emphasis on installing, configuring, modifying, and maintaining the database by means of structured query language and Enterprise Manager. Students will discuss data structures; indexed and direct file organizations; models of data, including hierarchical, network and relational; storage philosophies, data administration and analysis; design; and implementation. Students are required to demonstrate course objectives through the appropriate Oracle Database Administration certification exam and the fee for the exam is assessed upon enrollment in the program.')",
"(13, 'DBMS', 210, 'Database Design and Development', 'Emphasizes the development of advanced applications in database management using software such as Access. Students will learn methods of data import and export; advanced table properties; advanced queries and basic SQL; form and report design; macros for automating database tasks; and building menu-driven applications. Students will produce a cumulative final database application project. Students are required to demonstrate course objectives through the appropriate Microsoft certification exam preparation material and the fee for the exam is assessed upon enrollment in the course.')",
"(14, 'INFM', 109, 'Informatics Fundamentals', 'Introduces the student to terminology, concepts, theory, and fundamental skills used to implement information systems and functions in a wide variety of applications from small to enterprise organizations. Topics include the history of and trends in computing, operating systems, security, cloud implementations and other concepts associated with applying the principles of good information management to the organization. A brief introduction to word processing and spreadsheets is included as part of a skill set that students will use throughout their careers in informatics.')",
"(15, 'INFM', 209, 'Informatics and HCI', 'Examines the various needs, uses, and consequences of information technology in organizational contexts and how it involves the study, planning, and design of the interaction between people and computers. Students will discover how problem solving is integrated with information technology including introductions to information representation, relational databases, system design, propositional logic, and cutting-edge technologies. Students will be introduced to the analysis of human factors and the design of computer application interfaces including a perspective of human-computing interaction designs in future technologies. Students will learn the concepts of human-computing interaction with a focus on implementation and testing. Students will be introduced to key social research perspectives, current and historical literature on the use of information and communication technologies.')",
"(16, 'INFM', 219, 'Business Intelligence and Report', 'Introduces students to technology and techniques used to effectively consolidate, arrange, and analyze vast amounts of data. Data analytics has become a highly sought after skill in many industries. Students will be introduced to data warehousing, business intelligence, and related topics such as decision support systems, data mining, web mining, and customer relationship management. Emphasis is placed on learning how to derive business value from large amounts of data.')",
"(17, 'SDEV', 120, 'Computing Logic', 'Introduces the student to algorithms, logic development and flowcharting as tools used to document computer logic. Students will study math concepts and the importance to computer development. Included areas of study are base numbering systems, truth tables, logic and relational operators. Other concepts covered are order of precedence, decision trees, security, different types of language approaches, and scripting. Students will practice skills such as listening, team building, work ethic, communications, documentation, and adaptability. Concepts will be demonstrated using basic scripting and simple programming code.')",
"(18, 'SDEV', 140, 'Introduction to Software Develop', 'Introduces students to concepts and practices of programming languages and software development. Students are introduced to algorithms and development tools used to document/implement computer logic. Discusses the history of software development, the different types of programming such as real time processing, web/database applications, and different program development environments. Students are introduced to structured programming concepts such as basic control structures, variables, constants, arrays, procedures and functions; and advanced concepts such as lists, records, sorts and searches. Students are introduced to object-oriented software development. Concepts will be applied using basic scripting and/or simple programming code. Students will practice skills such as team building, work ethic, communication, documentation, and adaptability.')",
"(19, 'SDEV', 153, 'Web Site Development', 'Provides a basic understanding of the essential Web development skills and business practices that directly relate to Internet technologies used in Web site development. Students will learn to develop Web sites using Hypertext Markup Language and Cascading Style Sheets manually and with authoring tools. Students will work with images, create hyperlinks, tables, forms, and multimedia for Web pages. ')",
"(20, 'SDEV', 164, 'Mobile Application Develop.', 'Introduces students to concepts and practices of different programming and software development languages for mobile applications. Students will learn the software development life cycle for mobile devices including investigating requirements, feasibility, building, testing, deploying, and supporting the application. Concepts will be applied through creating hands-on applications for one or more platforms using current development environments and tools. Students will practice skills such as team building, work ethic, communication, documentation, and adaptability.')",
"(21, 'SDEV', 200, 'Software Development using Java', 'Provides a basic understanding of the fundamental concepts involved when using the Java programming development language. The emphasis is on logical program design using a modular approach involving task-oriented program functions. Object-oriented concepts such as methods, attributes, inheritance, exception handling, and polymorphism are utilized. Applications are developed using these concepts and include developing a graphical user interface, selecting forms and controls, assigning properties and writing code. Students are required to demonstrate course objectives through the appropriate Oracle Java certification exam and the fee for the exam is assessed upon enrollment in the course.')",
"(22, 'SDEV', 220, 'Software Development using Pytho', 'Provides an understanding of fundamental and advanced concepts of the Python programming language. The emphasis will be on creating industry standard programs using current programming design software. Students will learn basic programming concepts such as sequence, iteration and decision structures; variables and constants; and functions and advanced concepts such as searches, sorts, collections, dictionaries, arrays, and linked lists. Students will learn the concepts of object-oriented programming using classes, inheritance and polymorphism. These skills will be practiced in a hands-on environment. Students will practice skills such as team building, work ethic, communication, documentation, and adaptability.')",
"(23, 'SDEV', 230, 'Software Development using C++', 'Covers topics in C++ programming language with emphasis on classes, advanced debugging techniques, pointers, dynamic memory allocation, and data allocation. Students will apply skills in a laboratory  environment. Students will be introduced to object-oriented design and programming concepts using C++ language features. Differences between C and C++ programming will be discussed.')",
"(24, 'SDEV', 250, 'Client-side Scripting Language a', 'Students will learn basic to intermediate client-side scripting aspects including the use of JavaScript and other tools as related to Web page development. Students will prepare client-side scripts using data types and variables, expressions and operators, functions, arrays and objects. Students will use these to interact with HTML components to create dynamic web content. Students will use scripts interacting with HTML forms, how to create, manipulate and save client-side cookies. Builds on the Web Site Development course, emphasizing the basics of client-side scripting and asynchronous Web communication serving as a natural complement to the Server-Side Scripting Languages and Tools course.')",
"(25, 'SDEV', 253, 'Server-side Scripting Language a', 'Students will learn basic to intermediate server-side scripting aspects including the use of PHP: hypertext preprocessor and other scripting tools. Students will prepare server-side scripts that work hand-in-hand with front-end Web languages such as Hyper Text Markup Language and JavaScript. Server-side scripts will be used to create dynamic Web interfaces. Builds on the Web Development course, emphasizing server-side scripting with database integration and serves as a natural complement to the Client-Side Scripting Languages and Tools course.')",
"(26, 'SDEV', 265, 'Software Development Projects', 'Students will develop a software product for an actual or simulated client who intends to use the product in a business environment. Students will form project teams to work through the full software  development life cycle from understanding the business requirements to delivering a functioning product. Students will explore software development issues, select the appropriate development life cycle, estimate effort and development times, understand risk management, and write functional software. Students will make a series of presentations and reports of the project progress to the client and instructor.')");

	}
?>